name       : gtk-sharp
version    : 2.12.45
release    : 6
source     :
    - http://download.mono-project.com/sources/gtk-sharp212/gtk-sharp-2.12.45.tar.gz : 02680578e4535441064aac21d33315daa009d742cab8098ac8b2749d86fffb6a
license    : GPL-2.0
component  : programming.library
summary    : GTKSharp
description: |
    Gtk# is a Mono/.NET binding to the cross platform Gtk2 GUI toolkit and the foundation of most GUI apps built with Mono.
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(mono)
    - pkgconfig(libglade-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
