name       : gtk-sharp
version    : 2.12.42
release    : 5
source     :
    - http://download.mono-project.com/sources/gtk-sharp212/gtk-sharp-2.12.42.tar.gz : f3b009bb73e3251378063b6f09786609cd4c061f3f8bf552f0ea663245c045c9
license    : GPL-2.0
component  : programming
summary    : GTKSharp
description: |
    Gtk# is a Mono/.NET binding to the cross platform Gtk+ GUI toolkit and the foundation of most GUI apps built with Mono.
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(mono)
    - pkgconfig(libglade-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
